#!/bin/bash

# check init system
if [ -d "/run/systemd/system" ]; then
    for file in /opt/ss/ssm-client/systemd/*; do
        if ! [ -f "/lib/systemd/system/$(basename ${file})" ]; then
            mv "${file}" /lib/systemd/system/
        fi
    done

    # backup ssm service files under /etc/systemd/system
    for file in /etc/systemd/system/ssm-{linux,mysql,mongodb,postgresql,proxysql}-metrics.service /etc/systemd/system/ssm-{mysql,mongodb}-queries.service /etc/systemd/system/ssm-mysql-tuning.service; do
        if ! [ -f "$file" ]; then
            continue
        fi

        mv "$file" "${file}.dpkg-old"
    done
elif [ -f "/sbin/upstart-udev-bridge" ] || ([ -f "/sbin/init" ] && [ "$(/sbin/init --version)" == "init (upstart"* ]); then
    for file in /opt/ss/ssm-client/init/*; do
        if ! [ -f "/etc/init/$(basename ${file})" ]; then
            mv "${file}" /etc/init/
        fi
    done
else
    for file in /opt/ss/ssm-client/init.d/*; do
        if ! [ -f "/etc/init.d/$(basename ${file})" ]; then
            mv "${file}" /etc/init.d/
        fi
    done
fi
rm -rf /opt/ss/ssm-client/{systemd,init.d,init}

# install
if [ "$1" == "configure" ] && [ -z "$2" ]; then
    # copy conf files
    for file in /opt/ss/ssm-client/config/*; do
        mv "${file}" /opt/ss/ssm-client/
    done
    [ -z "$(ls -A /opt/ss/ssm-client/config)" ] || rm -rf /opt/ss/ssm-client/config

# upgrade
elif [ "$1" == "configure" ]; then
    # Upgrade from PMM
    if [ -f /opt/ss/percona/pmm-client/pmm.yml ]; then
        cp -n /opt/ss/percona/pmm-client/pmm.yml /opt/ss/ssm-client/ssm.yml
    fi
    if [ -f /opt/ss/percona/pmm-client/server.crt ]; then
        cp -n /opt/ss/percona/pmm-client/server.crt /opt/ss/ssm-client/server.crt
    fi
    if [ -f /opt/ss/percona/pmm-client/server.key ]; then
        cp -n /opt/ss/percona/pmm-client/server.key /opt/ss/ssm-client/server.key
    fi
    if [ -d /opt/ss/percona/qan-agent ] && [ ! -f /opt/ss/qan-agent/config/agent.conf ]; then
        find /opt/ss/percona/qan-agent -maxdepth 1 ! -path /opt/ss/percona/qan-agent ! -name bin -exec cp -r "{}" /opt/ss/qan-agent/ \;
    fi

    # from 9.x going forward, we leave the new config files as .new files
    if ! [ -f /opt/ss/ssm-client/.old-version ] || [[ "$(cat /opt/ss/ssm-client/.old-version)" =~ ^[vV]?[0-8][.] ]]; then
        :
    else
        for file in /opt/ss/ssm-client/config/*; do
            if ! [ -f /opt/ss/ssm-client/${file#/opt/ss/ssm-client/config/} ]; then
                mv "${file}" /opt/ss/ssm-client/
            elif diff -s "$file" /opt/ss/ssm-client/${file#/opt/ss/ssm-client/config/} >/dev/null; then
                :
            else
                mv "${file}" /opt/ss/ssm-client/${file#/opt/ss/ssm-client/config/}.new
            fi
        done
    fi

    ssm-admin upgrade
fi

rm -rf /opt/ss/percona